name: best_flutter_ui_templates
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"
# Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.2
    font_awesome_flutter: ^10.1.0
    flutter_rating_bar: ^4.0.1
    intl: ^0.17.0
    animations: ^2.0.3
    flutter_svg: ^1.1.0
    intl_utils: ^2.8.2
    image_picker: ^0.8.7
    shared_preferences: ^2.0.18
    dio: ^5.0.2
    syncfusion_flutter_charts: ^20.4.54
    syncfusion_flutter_datepicker: ^20.4.54
    firebase_core: ^2.8.0
    firebase_messaging: ^14.3.0
    firebase_auth : ^4.1.3
    flutter_easyloading: ^3.0.5
    adaptive_scrollbar: ^2.1.2
    flutter_launcher_icons: ^0.12.0
    flutter_facebook_auth: '^3.5.0'
    google_sign_in: ^6.0.2
    flutter_spinbox: ^0.13.0
    flutter_native_splash: ^2.2.19
    url_launcher: ^6.1.10
    internet_connection_checker: ^1.0.0+1
    share: ^2.0.4
    change_app_package_name: ^1.1.0
    timeago: ^3.2.2
dev_dependencies:
    flutter_test:
        sdk: flutter

        
flutter_icons:
  image_path: "assets/icons/luncher.png"
  # image_path_android: "assets/icons/payment.png"
  # image_path_ios: "assets/icons/payment.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/icons/
        # - assets/design_course/
        - assets/fitness_app/
        # - assets/hotel/
        - assets/introduction_animation/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400
        - family: MyIcon
          fonts:
              - asset: assets/fonts/iconfont.ttf 
                weight: 100
                
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: ar # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl
    project_id: # Get it from the https://app.localizely.com/projects page.
    branch: # Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
    upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
    upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
    download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
    download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false

flutter_native_splash:
  color: "#000000"
  image: assets/icons/logo.png
  android: true
  ios: true